### ISSUE TITLE
Is there somewhere a mapping from the emoji to grab the right file?

### ISSUE THREAD

**Issue by DirkBoer** [microsoft/fluentui-emoji#114]
I want to replace the emojis in my app to keep them consistent. IOS emojis look pretty outdated nowadays.

I'm thinking about uploading them to Azure Storage under the emoji character + svg.

So I can easily replace my emojis in my code by: storage.example.com/emojis/🥲.svg

Is there anywhere a mapping from the emoji codes to the right folder in this repository?

so I want to map 🥲 to https://github.com/microsoft/fluentui-emoji/blob/main/assets/Smiling%20face%20with%20tear/Flat/smiling_face_with_tear_flat.svg or something similar.

is there any way to map these so I can upload them to my storage? Or any other easier way to go from the emoji character to the flat style svgs?

In the end the greatest way would be to place them somewhere on a CDN.

**Comment by spencer-nelson** [comment]
There isn't one at the moment. At the base directory for all the emoji is a metadata.json file with that information, though. Note that if you need skin tone information, you'll have to pay attention to that, but if you just write a script to read through the directories and look into the metadata.json file for each, you can create your own mapping.
