### ISSUE TITLE
man_deaf and wonam_deaf are wrong way around

### ISSUE THREAD

**Issue by malte9799** [microsoft/fluentui-emoji#121]
https://github.com/microsoft/fluentui-emoji/tree/main/assets/Man%20deaf
https://github.com/microsoft/fluentui-emoji/blob/main/assets/Woman%20deaf

[man_deaf_3d_medium:](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Man%20deaf/Medium/3D/man_deaf_3d_medium.png)
![man_deaf_3d_medium](https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Man%20deaf/Medium/3D/man_deaf_3d_medium.png)

[woman_deaf_3d_medium:](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Woman%20deaf/Medium/3D/woman_deaf_3d_medium.png)
![woman_deaf_3d_medium](https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Woman%20deaf/Medium/3D/woman_deaf_3d_medium.png)

**Comment by Bronnel721** [comment]
I remember seeing this issue on my computer. I have no idea how this happened. No I'm not involved with the fluent emoji team.
