### ISSUE TITLE
Emoji Version 15.0?

### ISSUE THREAD

**Issue by malte9799** [microsoft/fluentui-emoji#123]

**Comment by Bronnel721** [comment]
It's _almost_ there. I don't work with them, but I know there's another branch:
https://github.com/microsoft/fluentui-emoji/tree/williamch/emoji15

**Comment by LockBlock-dev** [comment]
Is there anything preventing them from being merged? Everything seems ok to me..

**Comment by DellZHackintosh** [comment]
One of 🫨 images had a problem. It may causes that.

**Comment by willchavez** [comment]
Merged [yesterday](https://github.com/microsoft/fluentui-emoji/pull/143).
