### ISSUE TITLE
Some emoji lacking skin tone data

### ISSUE THREAD

**Issue by justsomederpystuff** [microsoft/fluentui-emoji#15]
First of all i'm incredibly thankful that you decided to open-source these.

I've tried to write a small script that convert the emoji into (codepoints).svg and noticed that certain emoji like `🤼‍♀️ woman wrestling` lack `unicodeSkintones` in their metadata.json despite having skin tone variants

Would it be possible to get this fixed or provide a download that has all files with just their codepoints as names?

**Comment by williamch-ms** [comment]
Thanks for opening this issue! @justsomederpystuff 

I wanted to ask if there was a way or code you used to detected the lack of `unicodeSkintones` and if there are other emojis that are missing it that need it.

**Comment by justsomederpystuff** [comment]
all emojis that i noticed were 
```txt
folded hands (🙏)
man genie (🧞‍♂️)
men with bunny ears (👯‍♂️)
men wrestling (🤼‍♂️)
man zombie (🧟‍♂️)
genie (🧞)
person in bed (🛌)
person in steamy room (🧖)
people wrestling (🤼)
zombie (🧟)
skier (⛷️)
woman genie (🧞‍♀️)
women with bunny ears (👯‍♀️)
women wrestling (🤼‍♀️)
woman zombie (🧟‍♀️)
```

my code effectively just went through all directories under `/assets/` and reported an error if there were any skintone subdirectories present yet no `unicodeSkintones` in metadata.json

In addition, `playground slide (🛝)` seems to be missing its Color directory.

**Comment by williamch-ms** [comment]
@justsomederpystuff created a PR to address the majority of this

The following emoji don't have unicode skin tone values according to [Unicode 14.0](https://unicode.org/emoji/charts/full-emoji-modifiers.html)

- men with bunny ears (👯‍♂️)
- men wrestling (🤼‍♂️)
- people wrestling (🤼)
- skier (⛷️)
- women with bunny ears (👯‍♀️)
- women wrestling (🤼‍♀️)

**Comment by Davr1** [comment]
I've noticed that some of the emojis justsomederpystuff mentioned are actually present in unrelated metadata files:
```
handshake: 🤝 🙏 🙏🏻 🙏🏼 🙏🏽 🙏🏾
(person) genie: 🧞 🧞‍♂️ 🧞‍♀️ 🧟 🧟‍♂️ 🧟‍♀️
people/person with bunny ears: 👯 👯‍♂️ 👯‍♀️ 🧖 🧖🏻 🧖🏼
```

**Comment by dav3shanahan** [comment]
why can't you change the skin tone color of emojis in Windows 11?
