### ISSUE TITLE
Mans shoe missed

### ISSUE THREAD

**Issue by Aghajari** [microsoft/fluentui-emoji#35]
Hi, The emoji set looks so Awesome. Thanks for open-sourcing this project! 
 
Only this two of the emojis did not follow the structure!
 - [Mans shoe](https://github.com/microsoft/fluentui-emoji/tree/main/assets/Mans%20shoe/3D) -> It's an empty svg!
 - [Heavy dollar sign](https://github.com/microsoft/fluentui-emoji/tree/main/assets/Heavy%20dollar%20sign/3D) -> There is no png file.

**Comment by JeLuF** [comment]
In both cases, there is an SVG file in the 3D folder instead of a PNG.

**Comment by Aghajari** [comment]
The first one is an empty svg file!

**Comment by JeLuF** [comment]
Yes. It is emtpy, but it shouldn't be there in the first place. The "3D"-folder should contain a PNG rendered version of the SVG file in the color/ directory:
https://github.com/microsoft/fluentui-emoji/blob/main/assets/Mans%20shoe/Color/mans_shoe_color.svg

**Comment by quintenser** [comment]
This issues been [fixed](https://github.com/microsoft/fluentui-emoji/pull/49/commits/6d0968723077096cc1639f70c24cd6b15da2c1d5) and therefor is ready to be closed.
