### ISSUE TITLE
Some "light" skin tone emojis have a yellowish colour

### ISSUE THREAD

**Issue by JeLuF** [microsoft/fluentui-emoji#42]
Most light skin tone emojis use the color FFD7C2 as skin color.
A few use FFDEA7 instead, which looks strange when used together with the others. These emojis are:

- Backhand index pointing down
- Backhand index pointing up
- Hand with fingers splayed
- Raised back of hand
- Raised hand
- Right-facing fist
- Vulcan salute

**Comment by JeLuF** [comment]
![image](https://user-images.githubusercontent.com/5852422/184716604-1bf8197f-2223-4b9d-879e-918d947d6d7a.png)
In Medium-Light, the accent color of the above emojis is identical to the skin color.

**Comment by jasoncuster** [comment]
Thanks @JeLuF - we've identified and updated the issue and will push an update this week.

**Comment by jasoncuster** [comment]
These have been updated. Please let us know if you see other issues.
