### ISSUE TITLE
Needs more weapons

### ISSUE THREAD

**Issue by jgarcianewemage** [microsoft/fluentui-emoji#48]
Lacks diversity in tools, vehicles and weapons for games and conflict maps

**Comment by DeveloperWOW64** [comment]
> Lacks diversity in tools, vehicles and weapons for games and conflict maps

That's true but I guess Microsoft doesn't want to create too many new emoji outside of the Unicode guideline unless they have a specific reason to, e.g. adding better support for representing the LGBTQIA+ community.

**Comment by jasoncuster** [comment]
Thanks for the note @jgarcianewemage - the Fluent emoji adhere to the unicode set. You can [request new ones here](https://unicode.org/emoji/proposals.html), but the consortium is _very_ selective on what gets added each year to keep the full set as maintainable as possible.

And we agree @DeveloperWOW64 with pushing for better support on LGBTQIA+ representation in the set.
