### ISSUE TITLE
Add an icon for the Baha'i Faith

### ISSUE THREAD

**Issue by SgtApple** [microsoft/fluentui-emoji#67]
Many of the world religions are available in the emoji set. It would be nice to see the Baha'i Faith represented. The most common symbol is a 9 pointed star. I am not an artist, so me making one would not do justice. But I just wanted to make the request.

**Comment by jasoncuster** [comment]
Hi @SgtApple - thanks for the idea! Currently the Fluent emoji follow the unicode set. You can [submit new ideas to the unicode backlog here](https://unicode.org/emoji/proposals.html).
