### ISSUE TITLE
Emoji missing

### ISSUE THREAD

**Issue by SplitMayo** [microsoft/fluentui-emoji#69]
Hello, i cannot find the star emoji face: 🤩

¿can you help me?

**Comment by 2n** [comment]
It seems to be named Star-struck.
https://github.com/microsoft/fluentui-emoji/blob/main/assets/Star-struck/3D/star-struck_3d.png
https://github.com/microsoft/fluentui-emoji/blob/main/assets/Star-struck/Color/star-struck_color.svg

**Comment by williamch-ms** [comment]
Closing, the start emoji face is under [main/assests/Star-struck](https://github.com/microsoft/fluentui-emoji/tree/main/assets/Star-struck).
