### ISSUE TITLE
A red cross should not be used

### ISSUE THREAD

**Issue by maekawa-mugi** [microsoft/fluentui-emoji#84]
A red cross is used in the hospital (U+1F3E5).
The Geneva Convention and Japanese law limit the use of the Red Cross to the Red Cross Society in principle.

Therefore, I propose that it should be changed to a blue asterisk instead.

**Comment by newbold** [comment]
I think they’re following some well-established patterns for hospital iconography: https://emojipedia.org/hospital/

In many parts of the world, hospitals are readily identified by red crosses.

**Comment by maekawa-mugi** [comment]
Sorry, the blue asterisk is the symbol used for ambulances.
Google and Apple appear to be addressing this issue by hollowing out the center.

I believe that a white background with horizontal and vertical lines is considered a red cross, and that changing the color of the cross or hollowing it out would work around the problem without destroying the impression.

With, this is only intended as a suggestion and concern, not a strong request. Past discussions appeared to be non-existent, but if the project master is confident in the pictorial artwork, please close this issue.

**Comment by maekawa-mugi** [comment]
Additional Info:
Mr. Shigeta (ex. Docomo), known as the father of the emoji, spoke about the hospital emoji on Twitter.
According to his story, the Red Cross pointed out that the emoji colors have been changed.

https://twitter.com/sigekun/status/24565482257
https://twitter.com/sigekun/status/1578740490325094402

**Comment by Dorapower** [comment]
https://en.wikipedia.org/wiki/Emblems_of_the_International_Red_Cross_and_Red_Crescent_Movement#Use_of_the_emblems

The restriction on the usage of red cross is defined in Geneva Conventions. 196 countries have ratified the conventions, not one country, not a few. Even local laws does not enforce the restriction it is still not acceptable to use it. And as the page listed, unauthorized use is directly violation of the law in Canada, Hong Kong, Singapore, UK, US and probably more counties.

I am not a law expertise, but as ms is a american company, it should follow american laws like the **Geneva Distinctive Emblems Protection Act of 2006**

**Comment by Download** [comment]
Knowing this makes me want to paint red crosses on everything!

I mean, reserving the right to use the cross, one of the most used symbols in history, in one of the primary colors?? How high does your power trip go??? I reserve the right to paint red crosses wherever I want them and the UN can come and arrest me... Pff sorry for the rant but some laws should be illegal imho...

**Comment by Lamparter** [comment]
> I mean, reserving the right to use the cross, one of the most used symbols in history, in one of the primary colors?? How high does your power trip go??? I reserve the right to paint red crosses wherever I want them and the UN can come and arrest me... Pff sorry for the rant but some laws should be illegal imho...

It's not exactly as it sounds - it's a specific colour in a specific drawing of a cross.
As in, drawn as shown:
![image](https://github.com/user-attachments/assets/e232ef5c-9451-4fba-b73e-5d74d2e97d08)
Microsoft's emoji is a red 'x' with a gradient - not quite the same.

**Comment by maekawa-mugi** [comment]
The Geneva Convention's restrictions on the use of the red cross do not require it to be a strict symbol.
In addition, not all red crosses are regulated. For example, in Japanese there is a kanji character "十" which means 10, but it is considered acceptable to write it in red.
The Geneva Convention and the laws and regulations of each country prohibit the use of the red cross indiscriminately.
This emoji is clearly inappropriate because it uses a red cross in the context of a hospital.

**Comment by Lamparter** [comment]
> This emoji cannot be used by government agencies of countries that have ratified the Geneva Convention.

That's correct, of course. I feel like GitHub is not the correct place to report this kind of legal vulnerability - more direct contact with Microsoft Corporation would be helpful as this repository is used solely to host OSS versions of emoji, it's i.e. it's not to be used for discussions like these

**Comment by Lamparter** [comment]
https://www.redcross.org.uk/about-us/what-we-do/protecting-people-in-armed-conflict/the-emblem
> The emblem of a red cross – with arms of equal length on a white background – is one of the most recognised symbols in the world

This is not a legal description of the Protected Emblems however this does give more clarity to exactly what the red cross is. The Han/Kanji character you referred to earlier '十' does not match this description.
