### ISSUE TITLE
File-Structure proposal

### ISSUE THREAD

**Issue by JumpingPistachio** [microsoft/fluentui-emoji#86]
The current folder-file structure is quite a mess. I see a relatively easy fix that I would be willing to work on. 
My proposal for the folder structure would be:
( - folder )
( * file   )

- root folder
  - (other folders)
  - assets 
    - example category 
      - example emoji
        - 3D
          * file.png
        - Flat
           * file.png
        - Color
          * file.png
        - High Contrast
          * file.png
      - another emoji
        - (all of the stuff)

etc.

**Comment by austinvach** [comment]
Would recommend aligning to the unicode structure: group > subgroup > emoji > emoji type (3D, Flat, Color, High Contrast) > file.

https://unicode.org/Public/emoji/15.1/emoji-test.txt
